### ISSUE TITLE
meta data for external submission missing

### ISSUE THREAD

**Issue by KBorm** [ProFormA/proformaxml#14]
For specifying an external submission (e.g. stored in a version control system) there is only one string which normally stores the URI. 
I need to know which type of version control system is used (SVN, GIT or whatsoever, the protocol cannot be used because the firewall only accepts http/https).
Therfore the type must be coded into the URI string which is not a good idea. 
=> metadata namespace for external submission? or additional type attribute...

**Comment by schmendrik** [comment]
I am not so sure that client systems handling the downloading of external submission and task files actually *need* to know about the type of version control used to store them.

Let's assume there are two types of version control systems: ones that require authorization when accessing task/submission resources (private repositories), and ones that make them publicly available without needing authorization (public repositories).

Let us also assume that these version controls are capable of providing downloadable direct links to these files. In Github and Gitlab, for example, direct links to files can be acquired by using the "raw" view for both plaintext and binary files.

In that case, we do not need version control tools (such as `git clone`) to download tasks and submissions. Client systems can use simple HTTP GET requests to get these files, or use tools that are readily available on linux systems. (In Windows, you may have to install them first.)

Here are a few examples of different protocols on how to use these tools and which HTTP headers are required for download requests.


# Protocols

## HTTP/HTTPS

### Downloading task/submission files from a public repository:
  - `curl -L -o task.zip https://raw.githubusercontent.com/ProFormA/examples/master/proforma_v2.0.x/ostfalia/task/helloWorld.zip`
    - L: follow redirects
  - `wget --no-check-certificate -O task.zip https://raw.githubusercontent.com/ProFormA/examples/master/proforma_v2.0.x/ostfalia/task/helloWorld.zip`
    -no-check-certificate because of: ERROR: certificate common name "www.github.com" doesn't match requested host name "raw.githubusercontent.com". To connect to xxx.company.com insecurely, use '--no-check-certificate'.

### Downloading files from private repositories:
  - Using Github and Gitlab as an example: the repository owner creates a repository user that has read-only access to the repository. The owner then creates an access token (let's call it 'myToken') for this user and distributes it to clients using the repository for downloading files.
    - `wget --header="Authorization: token myToken" --no-check-certificate -O task.zip https://raw.githubusercontent.com/privaterepo/tasks/master/sometask.zip`
    - `curl -H "Authorization: token myToken" -o task.zip -L https://raw.githubusercontent.com/privaterepo/tasks/master/sometask.zip`
  - If username and password are to be used instead of a token:
    - `wget --user username --password password <linkToFile>`
    - `curl -u username:password <linkToFile>`
    - or use HTTP Header: `"Authorization: basic username:password"` in your client system's code for HTTP GET requests (depending on the authorization schema used -- here, it is schema 'basic')

## FTP

  - `wget --ftp-user=user --ftp-password=passw <ftpAddress>`


# Pros
  - This is a generic approach that should work with every repository, be it version controlled (e.g. git) or not (e.g. CodeHarbor). If the assumption about the repository providing downloadable direct links is met, that is.
  - Clients would not need to `git clone` an entire task repository with possibly a large number of tasks to get to that one task, unless that's the client's goal.
  - The external-task/submission XSD types would not need to be extended
  - Clients would not have to worry about what version control tool (e.g. git, svn) needs to be used, the version of that tool, what command syntax needs to be used, and if that tool is available on the client's system at all
                                                                                                                                                                                         
# Cons
  - The client has to load the credentials from somewhere (e.g. config file with credentials per repository base URL) as opposed to the `git clone` approach where the client would just configure the credentials via a git command for every separate repository and not worry about authentification anymore

**Comment by KBorm** [comment]
I simply use the command line interface of the version control systems: 
SVN: svn export ....
GIT: git clone ....
And I want to stick to that approach ;-)

**Comment by schmendrik** [comment]
How would you handle FTP then or sites that do not provide a git or svn API (CodeHarbor)?

Edit: Turns out there is a git client (https://github.com/git-ftp/git-ftp) for FTP.

**Comment by KBorm** [comment]
I only need to cope with the installation of 'our clients' not with every possible installation in the world :-)
BTW There might be a better solution than 'git clone' for git without copying the whole repository. I have not yet implemented git acess.

**Comment by schmendrik** [comment]
Good point. Git clone would just clone the entire task repository with possibly hundreds of tasks. 

I cannot come up with a working solution to download a single file from a repository using git. The `git archive` might download a single file from a repository, but it does not support https with github.com. There is an open issue about it (https://github.com/isaacs/github/issues/554). Git archive with ssh might work, but that requires public/private key authentication, even for public repositories. So every client would need to create their own private/public key and register it with the repository owner, as opposed to being handed an access token by the repository owner. Access tokens do not work with ssh, only private/public authentication does. Furthermore, `git archive` retrieves the actual task.zip as a yet another tar or zip archive, so additional unzipping is required.

According to my research, Github supports the svn API, so you could technically do `svn export https://github.com/username/projectname/trunk/some/path path/to/taskfile` on a github repository, but that seems counter intuitive to me.

Another one that kind of works:
`git clone --no-checkout --depth 1 https://github.com/ProFormA/examples.git && cd examples && git checkout origin/master -- proforma_v2.0.x/ostfalia/task/helloWorld.zip`

But that seems overkill. It also downloads the .git directory along with the zip, and you still need to navigate through that path /ostfalia/task/helloWorld.zip on your file system.


I have updated my post above with pros and cons as I see them.

**Comment by KBorm** [comment]
According #13 I send debug information about the external submission to the LMS. In order to get this information I need to know how to interact with that external system. So, I need to know what system I deal with.

**Comment by schmendrik** [comment]
> According #13 I send debug information about the external submission to the LMS.

What is this debug information, exactly? 

I'm not trying to down play your need for using a VC tool. If you absolutely need git, then you need git. However, we are trying to find a solution that works for everyone. So we need to consider the use cases before we commit to a solution.

**Comment by KBorm** [comment]
The students work in groups. The submission URI is automatically generated with the group identifier. The students do not enter the URI. As far as I know the path of the student submission is often misspelled in the repository (or structure is invalid). So I mirror the URI in the response  so that the student / teacher / admin can see where the source code is exported from. I also add some information in order to identfiy the commit later on.
